[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DDA"
version = "1.0.0"
description = "A python implementation of the DDA algorithm"
authors = [{ name = "Ryan Lucido", email = "rjlucido12@gmail.com" }]